### ISSUE TITLE
[Enhancement] On mobile, the text on the filters should be bigger for better readability

### ISSUE THREAD

**Issue by Skylitmoon** [info442-aut21/b-team#84] opened 2021-11-22 18:22 UTC
Tested on MacOS Monterey and Google Chrome Version 96.0.4664.45. The text is a bit too small when the window size is set to mobile. Increasing the size of the text in the Filter box would increase readability.

**Comment by angelinapoltavskiy** [comment] 2021-11-24 17:24
will fix sizing of text in development sprint

**Comment by angelinapoltavskiy** [comment] 2021-11-24 17:26
duplicate of #75

**Closed by angelinapoltavskiy** 2021-11-24 17:26 UTC
Labels: duplicate, enhancement
